# Comment in the following to get borders around all widgets for debugging
# <Widget>:
#     canvas.after:
#         Color:
#             rgb: 0,1,0
#         Line:
#             rectangle: self.x+1,self.y+1,self.width-1,self.height-1
#             dash_offset: 5
#             dash_length: 3

#:include kv/customstyle.kv
#:include kv/mainwidget.kv
#:include kv/installscreen.kv
#:include kv/prefscreen.kv
