from __future__ import unicode_literals

launcher_name = 'Tactical Battlefield'
default_mods_dir = 'Tactical Battlefield'
icon = 'icons/tb.ico'
original_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/downloads/TB_Launcher.exe'
executable_name = 'TB_Launcher'
forum_url = 'http://tacticalbattlefield.net/forum'
domain = 'launcher.tacbf.com'
web_seeds_path = '/tacbf/updater/mods'
metadata_path = '/tacbf/updater/metadata.json'
torrents_path = '/tacbf/updater/torrents'
troubleshooting_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/wiki/Troubleshooting'
bugtracker_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/issues'
settings_directory = 'TacBF Launcher'
