from __future__ import unicode_literals

launcher_name = 'Frontline'
default_mods_dir = 'Frontline'
icon = 'icons/fl.ico'
original_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/downloads/FL_Launcher.exe'
executable_name = 'Frontline'
forum_url = 'https://discordapp.com/channels/173758987445993474/173758987445993474'
domain = 'launcher.frontline.frl'
web_seeds_path = '/mods'
metadata_path = '/metadata.json'
torrents_path = '/torrents'
troubleshooting_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/wiki/Troubleshooting'
bugtracker_url = 'https://bitbucket.org/tacbf_launcher/tacbf_launcher/issues'
settings_directory = 'Frontline Launcher'
